package com.edsp.core.service;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.sql.Timestamp;
import java.time.Instant;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.web.server.ResponseStatusException;

class AiAgentRunHistoryServiceTest {
    private JdbcTemplate jdbcTemplate;
    private AiAgentRunHistoryService service;

    @BeforeEach
    void setUp() {
        var dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:ai_run_history;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE");
        jdbcTemplate = new JdbcTemplate(dataSource);
        jdbcTemplate.execute("drop table if exists ai_agent_runs");
        jdbcTemplate.execute("""
            create table ai_agent_runs(
              id bigint generated by default as identity primary key,
              agent_key varchar(100), provider_key varchar(100), theme varchar(100), period varchar(30),
              model_name varchar(160), status varchar(30), source varchar(40),
              input_summary_json clob, output_summary_json clob, warning_summary_json clob,
              error_code varchar(100), started_at timestamp, finished_at timestamp
            )
            """);
        service = new AiAgentRunHistoryService(jdbcTemplate, new ObjectMapper());
    }

    @Test
    void listFiltersRunsAndReturnsSafeCounts() {
        insertRun(
            "fallback-template", "warning", "fallback-template", "security_overview", "last_7_days",
            "{\"alertCount\":3,\"openAlertCount\":2}",
            "{\"sectionCount\":2,\"titles\":[\"态势概览\",\"高风险信号\"]}",
            "[\"provider_fallback_used\"]"
        );
        insertRun(
            "cloud-openai-compatible", "passed", "llm", "rule_effectiveness", "last_30_days",
            "{\"alertCount\":5}",
            "{\"sectionCount\":1,\"titles\":[\"规则有效性\"]}",
            "[]"
        );

        var rows = service.list(new AiAgentRunHistoryService.HistoryFilter(
            20, "warning", "fallback-template", "fallback-template", "security_overview", "last_7_days"
        ));

        assertEquals(1, rows.size());
        assertEquals(2, rows.getFirst().sectionCount());
        assertEquals(1, rows.getFirst().warningCount());
        assertEquals("fallback-template", rows.getFirst().providerKey());
    }

    @Test
    void listClampsLimitToOneHundred() {
        for (int index = 0; index < 105; index++) {
            insertRun(
                "fallback-template", "warning", "fallback-template", "security_overview", "last_7_days",
                "{\"alertCount\":1}", "{\"sectionCount\":1,\"titles\":[\"态势概览\"]}", "[]"
            );
        }

        assertEquals(100, service.list(new AiAgentRunHistoryService.HistoryFilter(
            999, null, null, null, null, null
        )).size());
    }

    @Test
    void detailReturnsAllowlistedSummaryWithoutRawContent() {
        long id = insertRun(
            "fallback-template", "warning", "fallback-template", "security_overview", "last_7_days",
            "{\"alertCount\":3,\"openAlertCount\":2,\"payload_json\":\"raw-secret\"}",
            "{\"sectionCount\":3,\"titles\":[\"态势概览\",\"https://unsafe.example\",\"API Key: demo-key\"],\"content\":\"raw-response\"}",
            "[\"provider_fallback_used\",\"Bearer demo-token\"]"
        );

        var detail = service.detail(id);
        var serialized = detail.toString().toLowerCase();

        assertEquals(2, detail.inputSummary().metricKeys().size());
        assertEquals(1, detail.outputSummary().titles().size());
        assertEquals("态势概览", detail.outputSummary().titles().getFirst());
        assertEquals("ai_agent_warning_redacted", detail.warnings().get(1));
        assertFalse(serialized.contains("raw-secret"));
        assertFalse(serialized.contains("raw-response"));
        assertFalse(serialized.contains("unsafe.example"));
        assertFalse(serialized.contains("demo-key"));
        assertFalse(serialized.contains("demo-token"));
    }

    @Test
    void detailForMissingRunReturnsNotFound() {
        var error = assertThrows(ResponseStatusException.class, () -> service.detail(404));

        assertEquals("ai_agent_run_not_found", error.getReason());
    }

    private long insertRun(
        String providerKey,
        String status,
        String source,
        String theme,
        String period,
        String inputSummary,
        String outputSummary,
        String warnings
    ) {
        var startedAt = Timestamp.from(Instant.parse("2026-06-02T00:00:00Z"));
        var finishedAt = Timestamp.from(Instant.parse("2026-06-02T00:00:01Z"));
        jdbcTemplate.update("""
            insert into ai_agent_runs(
              agent_key, provider_key, theme, period, model_name, status, source,
              input_summary_json, output_summary_json, warning_summary_json,
              error_code, started_at, finished_at
            ) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            "security-insight-agent", providerKey, theme, period, "safe-model", status, source,
            inputSummary, outputSummary, warnings, "provider_fallback_used", startedAt, finishedAt
        );
        return jdbcTemplate.queryForObject("select max(id) from ai_agent_runs", Long.class);
    }
}
