package com.edsp.core.service;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;

import com.edsp.core.config.AiAgentProperties;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.List;
import java.util.Map;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;

class AiAgentRunServiceTest {
    @Test
    void storesSafeRunSummaryAndReturnsRecentRuns() {
        var dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:ai_runs;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE");
        var jdbcTemplate = new JdbcTemplate(dataSource);
        jdbcTemplate.execute("""
            create table ai_agent_runs(
              id bigint generated by default as identity primary key,
              agent_key varchar(100), provider_key varchar(100), theme varchar(100), period varchar(30),
              status varchar(30), source varchar(40), input_summary_json clob, output_summary_json clob,
              warning_summary_json clob, error_code varchar(100), started_at timestamp, finished_at timestamp
            )
            """);
        var mapper = new ObjectMapper();
        var context = new StubContextService(jdbcTemplate);
        var client = new StubPythonClient(mapper);
        var service = new AiAgentRunService(jdbcTemplate, mapper, context, client);

        var result = service.run(new AiAgentRunService.RunRequest(
            "security-insight-agent", "fallback-template", "last_7_days", "security_overview"
        ));

        assertEquals("fallback-template", result.source());
        assertEquals(1L, jdbcTemplate.queryForObject("select count(*) from ai_agent_runs", Long.class));
        assertEquals(1, service.recent(10).size());
        var outputSummary = jdbcTemplate.queryForObject(
            "select output_summary_json from ai_agent_runs limit 1",
            String.class
        );
        assertEquals(true, outputSummary.contains("\"titles\":[\"安全态势概览\"]"));
        assertFalse(outputSummary.contains("安全聚合摘要"));
    }

    private static class StubContextService extends AiAgentContextService {
        StubContextService(JdbcTemplate jdbcTemplate) {
            super(jdbcTemplate);
        }

        @Override
        public Map<String, Long> aggregate(String period) {
            return Map.of("alertCount", 1L);
        }
    }

    private static class StubPythonClient extends PythonAiAgentClient {
        StubPythonClient(ObjectMapper mapper) {
            super(mapper, new AiAgentProperties("http://127.0.0.1:1", 100, true));
        }

        @Override
        public AgentResponse run(AgentRequest request) {
            return new AgentResponse(
                request.agentKey(), request.providerKey(), request.period(), request.theme(),
                "fallback-template", "warning", List.of(new Section("安全态势概览", "安全聚合摘要")), List.of()
            );
        }
    }
}

