package com.edsp.core.service;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;

import java.util.Map;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;

class AiAgentContextServiceTest {
    private JdbcTemplate jdbcTemplate;

    @BeforeEach
    void setUp() {
        var dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:ai_context;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE");
        jdbcTemplate = new JdbcTemplate(dataSource);
        jdbcTemplate.execute("drop all objects");
        jdbcTemplate.execute("create table raw_events(id bigint generated by default as identity, received_at timestamp default current_timestamp)");
        jdbcTemplate.execute("create table standard_events(id bigint generated by default as identity, created_at timestamp default current_timestamp)");
        jdbcTemplate.execute("create table alert_decisions(id bigint generated by default as identity, decision varchar(30), created_at timestamp default current_timestamp)");
        jdbcTemplate.execute("create table alerts(id bigint generated by default as identity, status varchar(30), severity varchar(30), created_at timestamp default current_timestamp)");
        jdbcTemplate.execute("create table ingestion_plan_sync_runs(id bigint generated by default as identity, status varchar(30), started_at timestamp default current_timestamp)");
        jdbcTemplate.execute("create table notification_deliveries(id bigint generated by default as identity, created_at timestamp default current_timestamp)");
        jdbcTemplate.update("insert into raw_events default values");
        jdbcTemplate.update("insert into standard_events default values");
        jdbcTemplate.update("insert into alert_decisions(decision) values ('matched'), ('not_matched'), ('error')");
        jdbcTemplate.update("insert into alerts(status, severity) values ('open', 'critical')");
        jdbcTemplate.update("insert into ingestion_plan_sync_runs(status) values ('warning')");
        jdbcTemplate.update("insert into notification_deliveries default values");
        jdbcTemplate.update("insert into raw_events(received_at) values (timestamp '2020-01-01 00:00:00')");
        jdbcTemplate.update("insert into standard_events(created_at) values (timestamp '2020-01-01 00:00:00')");
        jdbcTemplate.update("insert into alert_decisions(decision, created_at) values ('matched', timestamp '2020-01-01 00:00:00')");
        jdbcTemplate.update("insert into notification_deliveries(created_at) values (timestamp '2020-01-01 00:00:00')");
    }

    @Test
    void aggregatesAllowlistedCountsOnly() {
        Map<String, Long> context = new AiAgentContextService(jdbcTemplate).aggregate("last_7_days");

        assertEquals(1L, context.get("rawEventCount"));
        assertEquals(1L, context.get("standardEventCount"));
        assertEquals(3L, context.get("alertDecisionCount"));
        assertEquals(1L, context.get("matchedDecisionCount"));
        assertEquals(1L, context.get("openAlertCount"));
        assertEquals(1L, context.get("criticalAlertCount"));
        assertEquals(1L, context.get("warningSyncCount"));
        assertEquals(1L, context.get("notificationDeliveryCount"));
        assertFalse(context.containsKey("payload_json"));
        assertFalse(context.containsKey("config_json"));
    }
}
