server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: edsp-auth
  cloud:
    nacos:
      discovery:
        enabled: ${NACOS_ENABLED:true}
        server-addr: ${NACOS_ADDR:nacos:8848}

management:
  endpoints:
    web:
      exposure:
        include: health,info
